// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace RomanConverter_XAML.UITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = Microsoft.VisualStudio.TestTools.UITest.Input.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Test for return of I when 1 passed in
        /// </summary>
        public void AssertMethod1()
        {
            #region Variable Declarations
            XamlText uIResultBlockText = this.UIRomanConverter_XAMLWindow.UIResultBlockText;
            #endregion

            // Verify that the 'DisplayText' property of 'resultBlock' label equals 'I'
            Assert.AreEqual(this.AssertMethod1ExpectedValues.UIResultBlockTextDisplayText, uIResultBlockText.DisplayText, "1 -> I");
        }
        
        /// <summary>
        /// AssertReturnValue_II - Use 'AssertReturnValue_IIExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertReturnValue_II()
        {
            #region Variable Declarations
            XamlText uIResultBlockText = this.UIRomanConverter_XAMLWindow.UIResultBlockText;
            #endregion

            // Verify that the 'DisplayText' property of 'resultBlock' label equals 'II'
            Assert.AreEqual(this.AssertReturnValue_IIExpectedValues.UIResultBlockTextDisplayText, uIResultBlockText.DisplayText);
        }
        
        #region Properties
        public virtual AssertMethod1ExpectedValues AssertMethod1ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod1ExpectedValues == null))
                {
                    this.mAssertMethod1ExpectedValues = new AssertMethod1ExpectedValues();
                }
                return this.mAssertMethod1ExpectedValues;
            }
        }
        
        public virtual AssertReturnValue_IIExpectedValues AssertReturnValue_IIExpectedValues
        {
            get
            {
                if ((this.mAssertReturnValue_IIExpectedValues == null))
                {
                    this.mAssertReturnValue_IIExpectedValues = new AssertReturnValue_IIExpectedValues();
                }
                return this.mAssertReturnValue_IIExpectedValues;
            }
        }
        
        public UIRomanConverter_XAMLWindow UIRomanConverter_XAMLWindow
        {
            get
            {
                if ((this.mUIRomanConverter_XAMLWindow == null))
                {
                    this.mUIRomanConverter_XAMLWindow = new UIRomanConverter_XAMLWindow();
                }
                return this.mUIRomanConverter_XAMLWindow;
            }
        }
        #endregion
        
        #region Fields
        private AssertMethod1ExpectedValues mAssertMethod1ExpectedValues;
        
        private AssertReturnValue_IIExpectedValues mAssertReturnValue_IIExpectedValues;
        
        private UIRomanConverter_XAMLWindow mUIRomanConverter_XAMLWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class AssertMethod1ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'DisplayText' property of 'resultBlock' label equals 'I'
        /// </summary>
        public string UIResultBlockTextDisplayText = "I";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertReturnValue_II'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class AssertReturnValue_IIExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'DisplayText' property of 'resultBlock' label equals 'II'
        /// </summary>
        public string UIResultBlockTextDisplayText = "II";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIRomanConverter_XAMLWindow : XamlWindow
    {
        
        public UIRomanConverter_XAMLWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "RomanConverter_XAML";
            this.SearchProperties[XamlControl.PropertyNames.ClassName] = "Windows.UI.Core.CoreWindow";
            this.WindowTitles.Add("RomanConverter_XAML");
            #endregion
        }
        
        #region Properties
        public XamlEdit UITextBoxEdit
        {
            get
            {
                if ((this.mUITextBoxEdit == null))
                {
                    this.mUITextBoxEdit = new XamlEdit(this);
                    #region Search Criteria
                    this.mUITextBoxEdit.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "textBox";
                    this.mUITextBoxEdit.WindowTitles.Add("RomanConverter_XAML");
                    #endregion
                }
                return this.mUITextBoxEdit;
            }
        }
        
        public XamlButton UISubmitButton
        {
            get
            {
                if ((this.mUISubmitButton == null))
                {
                    this.mUISubmitButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUISubmitButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "button";
                    this.mUISubmitButton.WindowTitles.Add("RomanConverter_XAML");
                    #endregion
                }
                return this.mUISubmitButton;
            }
        }
        
        public XamlText UIResultBlockText
        {
            get
            {
                if ((this.mUIResultBlockText == null))
                {
                    this.mUIResultBlockText = new XamlText(this);
                    #region Search Criteria
                    this.mUIResultBlockText.SearchProperties[XamlText.PropertyNames.AutomationId] = "resultBlock";
                    this.mUIResultBlockText.WindowTitles.Add("RomanConverter_XAML");
                    #endregion
                }
                return this.mUIResultBlockText;
            }
        }
        #endregion
        
        #region Fields
        private XamlEdit mUITextBoxEdit;
        
        private XamlButton mUISubmitButton;
        
        private XamlText mUIResultBlockText;
        #endregion
    }
}
